var planeta=planeta||{};$.support.cors=true;planeta.utils=planeta.utils||{};planeta.utils.isDebug=true;planeta.utils.log=function(a){planeta.utils.isDebug&&console.log(a)};planeta.utils.dir=function(a){planeta.utils.isDebug&&console.dir(a)};planeta.utils.pad=function(a,d){a="00"+a;return a.substr(a.length-d)};planeta.utils.trackEvent=function(a){planeta.utils.log("track "+a);var d=new Image;d.src=a};
planeta.utils.trackGAEvent=function(a,d,c,e){try{planeta.utils.log("trackGAEvent "+a+" "+d+" "+c+" "+e);pageTracker._trackEvent(a,d,c,e,false)}catch(b){console.log(b)}};planeta.utils.getTime=function(a){var d=Math.round(a);a=d%60;var c=Math.floor(d/60%60);d=Math.floor(d/3600);return d>0?planeta.utils.pad(d,2)+":"+planeta.utils.pad(c,2)+":"+planeta.utils.pad(a,2):planeta.utils.pad(c,2)+":"+planeta.utils.pad(a,2)};
planeta.utils.createCookie=function(a,d,c){if(c){var e=new Date;e.setTime(e.getTime()+c*24*60*60*1000);c="; expires="+e.toGMTString()}else c="";document.cookie=escape(a)+"="+escape(d)+c+"; path=/"};planeta.utils.readCookie=function(a){a=escape(a)+"=";for(var d=document.cookie.split(";"),c=0;c<d.length;c++){for(var e=d[c];e.charAt(0)===" ";)e=e.substring(1,e.length);if(e.indexOf(a)===0)return unescape(e.substring(a.length,e.length))}return null};
planeta.utils.eraseCookie=function(a){createCookie(a,"",-1)};
planeta.utils.xml2json=function(a,d){var c={toObj:function(e){var b={};if(e.nodeType==1){if(e.attributes.length)for(var g=0;g<e.attributes.length;g++)b["@"+e.attributes[g].nodeName]=(e.attributes[g].value||"").toString();if(e.firstChild){for(var i=g=0,f=false,h=e.firstChild;h;h=h.nextSibling)if(h.nodeType==1)f=true;else if(h.nodeType==3&&h.nodeValue.match(/[^ \f\n\r\t\v]/))g++;else h.nodeType==4&&i++;if(f)if(g<2&&i<2){c.removeWhite(e);for(h=e.firstChild;h;h=h.nextSibling)if(h.nodeType==3)b["#text"]=
c.escape(h.nodeValue);else if(h.nodeType==4)b["#cdata"]=c.escape(h.nodeValue);else if(b[h.nodeName])if(b[h.nodeName]instanceof Array)b[h.nodeName][b[h.nodeName].length]=c.toObj(h);else b[h.nodeName]=[b[h.nodeName],c.toObj(h)];else b[h.nodeName]=c.toObj(h)}else if(e.attributes.length)b["#text"]=c.escape(c.innerXml(e));else b=c.escape(c.innerXml(e));else if(g)if(e.attributes.length)b["#text"]=c.escape(c.innerXml(e));else b=c.escape(c.innerXml(e));else if(i)if(i>1)b=c.escape(c.innerXml(e));else for(h=
e.firstChild;h;h=h.nextSibling)b["#cdata"]=c.escape(h.nodeValue)}if(!e.attributes.length&&!e.firstChild)b=null}else if(e.nodeType==9)b=c.toObj(e.documentElement);else alert("unhandled node type: "+e.nodeType);return b},toJson:function(e,b,g){var i=b?'"'+b+'"':"";if(e instanceof Array){for(var f=0,h=e.length;f<h;f++)e[f]=c.toJson(e[f],"",g+"\t");i+=(b?":[":"[")+(e.length>1?"\n"+g+"\t"+e.join(",\n"+g+"\t")+"\n"+g:e.join(""))+"]"}else if(e==null)i+=(b&&":")+"null";else if(typeof e=="object"){f=[];for(h in e)f[f.length]=
c.toJson(e[h],h,g+"\t");i+=(b?":{":"{")+(f.length>1?"\n"+g+"\t"+f.join(",\n"+g+"\t")+"\n"+g:f.join(""))+"}"}else i+=typeof e=="string"?(b&&":")+'"'+e.toString()+'"':(b&&":")+e.toString();return i},innerXml:function(e){var b="";if("innerHTML"in e)b=e.innerHTML;else{var g=function(i){var f="";if(i.nodeType==1){f+="<"+i.nodeName;for(var h=0;h<i.attributes.length;h++)f+=" "+i.attributes[h].nodeName+'="'+(i.attributes[h].nodeValue||"").toString()+'"';if(i.firstChild){f+=">";for(h=i.firstChild;h;h=h.nextSibling)f+=
g(h);f+="</"+i.nodeName+">"}else f+="/>"}else if(i.nodeType==3)f+=i.nodeValue;else if(i.nodeType==4)f+="<![CDATA["+i.nodeValue+"]]\>";return f};for(e=e.firstChild;e;e=e.nextSibling)b+=g(e)}return b},escape:function(e){return e.replace(/[\\]/g,"\\\\").replace(/[\"]/g,'\\"').replace(/[\n]/g,"\\n").replace(/[\r]/g,"\\r")},removeWhite:function(e){e.normalize();for(var b=e.firstChild;b;)if(b.nodeType==3)if(b.nodeValue.match(/[^ \f\n\r\t\v]/))b=b.nextSibling;else{var g=b.nextSibling;e.removeChild(b);b=
g}else{b.nodeType==1&&c.removeWhite(b);b=b.nextSibling}return e}};if(a.nodeType==9)a=a.documentElement;a=c.toJson(c.toObj(c.removeWhite(a)),a.nodeName,"\t");return"{\n"+d+(d?a.replace(/\t/g,d):a.replace(/\t|\n/g,""))+"\n}"};
planeta.utils.getVAST=function(a,d,c){a+=/\?/.test(a)?"&":"?";a=a+"pr="+Math.floor(Math.random()*1000000);var e=new Date,b=e.getDate(),g=e.getDay();e=e.getHours();var i="b",f=navigator.userAgent.toLowerCase(),h="";if(/android/i.test(f))h=Math.max(window.screen.width,window.screen.height)<=1280?3:4;else if(/iphone/i.test(f)||/ipod/i.test(f))h=1;else if(/ipad/i.test(f))h=2;else if(/windows phone/i.test(f)||/iemobile/i.test(f))h=5;f=d.player.isFullScreen()?0:1;a=a.replace(/%pt%/g,i).replace(/%pd%/g,
b).replace(/%pw%/g,g).replace(/%pv%/g,e);a=a.replace(/%device_type%/g,h).replace(/%fullscreen%/g,f);a=a.replace(/\$pt\$/g,i).replace(/\$pd\$/g,b).replace(/\$pw\$/g,g).replace(/\$pv\$/g,e);a=a.replace(/\$device_type\$/g,h).replace(/\$fullscreen\$/g,f);b="";b=d.player.placeholder.clientWidth;g=d.player.placeholder.clientHeight;b=b>1280&&g>720?"3":b>960&g>540&&b<=1280&&g<=720?"2":b>640&g>360&&b<=960&&g<=540?"1":b>400&g>225&&b<=640&&g<=360?"0":"4";a=a.replace(/%screen_size%/g,b);a=a.replace(/\$screen_size\$/g,
b);b=3;b=d.player.config.is_embed?d.player.config.autoplay?3:1:d.player.config.autoplay?2:0;a=a.replace(/%puid4%/g,""+b);a=a.replace(/\$puid4\$/g,""+b);b=parent!==window;g=null;g=b?document.referrer:top.location;a=a.replace(/%dl%/g,encodeURIComponent(g));a=a.replace(/\$dl\$/g,encodeURIComponent(g));adfoxLPD.prepareLink(a,function(m,l){planeta.utils.trackGAEvent("advertisement","ad_vast_request",d.type,0);planeta.utils.log("planeta.utils.getVAST: parsing "+l);if(/http/.test(l)&&/msie/.test(navigator.userAgent.toLowerCase())&&
window.XDomainRequest){var k=new window.XDomainRequest;k.open("GET",l);k.onload=function(){var j=new ActiveXObject("Microsoft.XMLDOM");j.async=false;j.loadXML(k.responseText);d.handleVAST($.parseJSON(planeta.utils.xml2json(j,"")),c)};k.onerror=function(){planeta.utils.log("planeta.utils.getVAST: Error 1!");d.handleVAST(null,c)};k.send()}else $.ajax({type:"GET",crossDomain:true,url:l,dataType:"xml",success:function(j){d.handleVAST($.parseJSON(planeta.utils.xml2json(j,"")),c)},error:function(j){planeta.utils.log("planeta.utils.getVAST: Error 2!");
planeta.utils.dir(j);d.handleVAST(null,c)}})})};var alertFallback=false;if(typeof console==="undefined"||typeof console.log==="undefined"){console={};console.log=alertFallback?function(a){alert(a)}:function(){}}
planeta.Player=function(a){this.config={};$.extend(this.config,a);this.postrollJustShown=this.prerollShown=false;this.playingAd=this.muteunmute=this.timebar=this.volumeticker=this.volumelevel=this.volumebar=this.fullscreen=this.timetooltip=this.progressticker=this.progressbar=this.playpause=this.controls=this.video=this.wrapper=this.placeholder=this.hideTimerId=0;a=navigator.userAgent.toLowerCase();if(/iphone/i.test(a)||/ipod/i.test(a)||/ipad/i.test(a)||/android/i.test(a))this.config.autoplay=false};
planeta.Player.prototype={onLoadStart:function(a){planeta.utils.log("onLoadStart");planeta.utils.dir(a)},onProgress:function(){},onSuspend:function(){},onAbort:function(){planeta.utils.log("onAbort")},onEmptied:function(){planeta.utils.log("onEmptied")},onStalled:function(){planeta.utils.log("onStalled")},onLoadedMetadata:function(a){planeta.utils.log("onLoadedMetadata");planeta.utils.dir(a)},onLoadedData:function(){planeta.utils.log("onLoadedData")},onCanPlay:function(){planeta.utils.log("onCanPlay")},
onCanPlayThrough:function(){planeta.utils.log("onCanPlayThrough")},onPlaying:function(){planeta.utils.log("onPlaying");$(this.playpause).addClass("po-pause").removeClass("po-play").attr("title","\u041e\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u0432\u0438\u0434\u0435\u043e")},onWaiting:function(){planeta.utils.log("onWaiting")},onSeeking:function(){planeta.utils.log("onSeeking")},onSeeked:function(){planeta.utils.log("onSeeked")},
getDuration:function(){return isNaN(this.video.duration)?0:this.video.duration},onDurationChange:function(){planeta.utils.log("onDurationChange");$(this.timebar).text(planeta.utils.getTime(this.getCurrentTime())+" / "+planeta.utils.getTime(this.getDuration()))},getCurrentTime:function(){return this.video.currentTime},setCurrentTime:function(a){this.video.currentTime=a},updateTimebar:function(){var a=this.getCurrentTime(),d=this.getDuration();$(this.timebar).text(planeta.utils.getTime(a)+" / "+planeta.utils.getTime(d));
var c=$(this.progressticker),e=$(this.progressbar);e.width()!=0&&c.css({left:a/d*e.width()-10})},onTimeUpdate:function(){this.updateTimebar()},togglePlayPause:function(){planeta.utils.log("togglePlayPause");if(this.isPaused()||this.isEnded()){planeta.utils.log("togglePlayPause -> play()");this.play()}else{planeta.utils.log("togglePlayPause -> pause()");this.pause()}},play:function(){planeta.utils.log("play: this.getCurrentTime()="+this.getCurrentTime()+", this.prerollShown="+this.prerollShown);if(this.getCurrentTime()<
0.01&&!this.prerollShown){typeof this.config.is_stream==="undefined"||this.config.is_stream==false?planeta.utils.trackGAEvent("video","video_start",this.config.title,this.config.videoId):planeta.utils.trackGAEvent("stream","stream_start",this.config.title,this.config.videoId);this.video.play();this.prerollShown=true;new planeta.AdController(this,"preroll")}else{this.video.play();typeof this.config.is_stream==="undefined"||this.config.is_stream==false?planeta.utils.trackGAEvent("video","video_resume",
this.config.title,this.config.videoId):planeta.utils.trackGAEvent("stream","stream_resume",this.config.title,this.config.videoId)}this.postrollJustShown=false},onPlay:function(){planeta.utils.log("onPlay")},pause:function(){this.video.pause();planeta.utils.log("pause");typeof this.config.is_stream==="undefined"||this.config.is_stream==false?planeta.utils.trackGAEvent("video","video_pause",this.config.title,this.config.videoId):planeta.utils.trackGAEvent("stream","stream_pause",this.config.title,this.config.videoId);
$(this.playpause).addClass("po-play").removeClass("po-pause").attr("title","\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u0432\u0438\u0434\u0435\u043e");new planeta.AdController(this,"pauseroll")},isPaused:function(){return this.video.paused},onPause:function(){},isEnded:function(){return this.video.ended},onRateChange:function(){planeta.utils.log("onRateChange")},onResize:function(){planeta.utils.log("resize")},
onVolumeChange:function(a){planeta.utils.log("volumechange");var d=a.target.volume;planeta.utils.createCookie("volume",d,30);a=a.target.id.substring(0,a.target.id.indexOf("_video"));$("#"+a+"_volumelevel").width(d*100+"%");$("#"+a+"_volumeticker").css({left:d*65-10})},onEnded:function(){if(!this.postrollJustShown){this.showController(1000000000);planeta.utils.log("ended(): showing postroll");if(typeof this.config.is_stream==="undefined"||this.config.is_stream==false){planeta.utils.trackEvent("http://www.planeta-online.tv/media/video/count/"+
this.config.videoId+".html");planeta.utils.trackGAEvent("video","video_end",this.config.title,this.config.videoId)}this.postrollJustShown=true;new planeta.AdController(this,"postroll");$(this.playpause).addClass("po-play").removeClass("po-pause").attr("title","\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u0432\u0438\u0434\u0435\u043e");planeta.utils.log("ended(): showing related")}},showController:function(a){a=
typeof a!=="undefined"?a:5000;$(this.controls).show();clearTimeout(this.hideTimerId);var d=this;this.hideTimerId=setTimeout(function(){d.hideController()},a)},hideController:function(){clearTimeout(this.hideTimerId);var a=this.getCurrentTime();$(this.timetooltip).hide();!isNaN(a)&&a!=0&&a!=this.getDuration()&&$(this.controls).hide()},makeUnselectable:function(a){a.addClass("po-unselectable").attr("unselectable","on").attr("draggable","false").on("dragstart",function(){return false});a.find("*").attr("draggable",
"false").attr("unselectable","on")},toggleMuteUnmute:function(){this.isMuted()?this.unmute():this.mute()},mute:function(){this.video.muted=true;typeof this.config.is_stream==="undefined"||this.config.is_stream==false?planeta.utils.trackGAEvent("video","video_mute",this.config.title,this.config.videoId):planeta.utils.trackGAEvent("stream","stream_mute",this.config.title,this.config.videoId);$(this.muteunmute).addClass("po-unmute").removeClass("po-mute").attr("title","\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0437\u0432\u0443\u043a")},
unmute:function(){this.video.muted=false;typeof this.config.is_stream==="undefined"||this.config.is_stream==false?planeta.utils.trackGAEvent("video","video_unmute",this.config.title,this.config.videoId):planeta.utils.trackGAEvent("stream","stream_unmute",this.config.title,this.config.videoId);$(this.muteunmute).addClass("po-mute").removeClass("po-unmute").attr("title","\u0412\u044b\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0437\u0432\u0443\u043a")},isMuted:function(){return this.video.muted},setVolume:function(a){this.video.volume=
a},toggleFullScreen:function(){this.isFullScreen()?this.closeFullScreen():this.goFullScreen()},goFullScreen:function(){var a=this.wrapper,d=a.requestFullScreen||a.webkitRequestFullScreen||a.mozRequestFullScreen||a.msRequestFullscreen;d.call(a);$(this.fullscreen).attr("title","\u0417\u0430\u043a\u0440\u044b\u0442\u044c \u043f\u043e\u043b\u043d\u043e\u044d\u043a\u0440\u0430\u043d\u043d\u044b\u0439 \u0440\u0435\u0436\u0438\u043c");this.makeUnselectable($("#"+this.config.placeholder));this.updateTimebar()},
closeFullScreen:function(){if(document.cancelFullScreen)document.cancelFullScreen();else if(document.mozCancelFullScreen)document.mozCancelFullScreen();else if(document.webkitCancelFullScreen)document.webkitCancelFullScreen();else document.msExitFullscreen&&document.msExitFullscreen();$(this.fullscreen).attr("title","\u0420\u0430\u0437\u0432\u0435\u0440\u043d\u0443\u0442\u044c \u043d\u0430 \u0432\u0435\u0441\u044c \u044d\u043a\u0440\u0430\u043d")},isFullScreen:function(){if(document.fullscreen)return true;
if(document.mozFullScreen)return true;if(document.webkitIsFullScreen)return true;if(document.msFullscreenElement)return true;return window.fullScreen||window.innerWidth==screen.width&&window.innerHeight==screen.height?true:false},updateProgress:function(){},bindVideoEvents:function(){planeta.utils.log("bindVideoEvents()");var a=this;$(this.video).on("dblclick",function(){a.toggleFullScreen();return false}).on("mousemove",function(){a.showController()}).on("contextmenu",function(){}).on("loadstart",
function(d){a.onLoadStart(d)}).on("progress",function(d){a.onProgress(d)}).on("suspend",function(d){a.onSuspend(d)}).on("abort",function(d){a.onAbort(d)}).on("emptied",function(d){a.onEmptied(d)}).on("stalled",function(d){a.onStalled(d)}).on("loadedmetadata",function(d){a.onLoadedMetadata(d)}).on("loadeddata",function(d){a.onLoadedData(d)}).on("canplay",function(d){a.onCanPlay(d)}).on("canplaythrough",function(d){a.onCanPlayThrough(d)}).on("playing",function(d){a.onPlaying(d)}).on("waiting",function(d){a.onWaiting(d)}).on("seeking",
function(d){a.onSeeking(d)}).on("seeked",function(d){a.onSeeked(d)}).on("durationchange",function(d){a.onDurationChange(d)}).on("timeupdate",function(d){a.onTimeUpdate(d)}).on("play",function(d){a.onPlay(d)}).on("pause",function(d){a.onPause(d)}).on("ratechange",function(d){a.onRateChange(d)}).on("resize",function(d){a.onResize(d)}).on("volumechange",function(d){a.onVolumeChange(d)}).on("ended",function(d){a.onEnded(d)})},initHTML5Player:function(){planeta.utils.log("initHTML5Player()");this.placeholder=
document.getElementById(this.config.placeholder);this.wrapper=document.getElementById(this.config.placeholder+"_wrapper");this.video=document.getElementById(this.config.placeholder+"_video");this.controls=document.getElementById(this.config.placeholder+"_controls");this.playpause=document.getElementById(this.config.placeholder+"_playpause");this.progressbar=document.getElementById(this.config.placeholder+"_progressbar");this.progressticker=document.getElementById(this.config.placeholder+"_progressticker");
this.timetooltip=document.getElementById(this.config.placeholder+"_timetooltip");this.fullscreen=document.getElementById(this.config.placeholder+"_fullscreen");this.volumebar=document.getElementById(this.config.placeholder+"_volumebar");this.volumelevel=document.getElementById(this.config.placeholder+"_volumelevel");this.volumeticker=document.getElementById(this.config.placeholder+"_volumeticker");this.timebar=document.getElementById(this.config.placeholder+"_timebar");this.muteunmute=document.getElementById(this.config.placeholder+
"_muteunmute");var a=this;$(this.placeholder).on("contextmenu",function(){return false}).on("mouseleave",function(){a.isPaused()||a.hideController()});$(this.controls).on("click",function(){if(a.isPaused()){planeta.utils.log('this.controls->on("click") -> running play()');a.play();return false}}).on("dblclick",function(){a.toggleFullScreen();return false}).on("mousemove",function(){a.isPaused()||a.showController()});$(this.playpause).on("click",function(c){c.stopImmediatePropagation();a.togglePlayPause()});
$(this.muteunmute).on("click",function(){a.toggleMuteUnmute()});$(this.volumebar).on("click",function(c){c=c.clientX-$(this).offset().left;if(c<0)c=0;if(c>64)c=64;a.setVolume(c/64)});$(this.progressbar).on("click",function(c){c.target.id.substring(0,c.target.id.indexOf("_progressbar"));var e=$(c.target).width(),b=0;b=c.offsetX==undefined?c.pageX-$(c.target).offset().left:c.offsetX;if(b<0)b=0;if(b>e)b=e;a.setCurrentTime(b/e*a.getDuration())}).on("mousemove",function(c){var e=c.target.id.substring(0,
c.target.id.indexOf("_progressbar")),b=$(c.target).width(),g=0;g=c.offsetX==undefined?c.pageX-$(c.target).offset().left:c.offsetX;c=a.getDuration();if(!(isNaN(b)||b==0||isNaN(g)||isNaN(c))){if(g<0)g=0;if(g>b)g=b;b=planeta.utils.getTime(g/b*c);$("#"+e+"_timetooltip").html(b).css({left:g+"px"}).show()}});$(this.progressticker).on("mousemove",function(c){var e=c.target.id.substring(0,c.target.id.indexOf("_progressticker")),b=$("#"+e+"_progressbar").width(),g=0;g=c.offsetX==undefined?c.pageX-$(c.target).offset().left:
c.offsetX;c=a.getDuration();if(!(isNaN(b)||b==0||isNaN(g)||isNaN(c))){if(g<0)g=0;if(g>b)g=b;var i=parseInt($("#"+e+"_progressticker").css("left"));g=i+g;b=g/b*c;if(b>=0){b=planeta.utils.getTime(b);$("#"+e+"_timetooltip").html(b).css({left:g+"px"}).show()}}});$(this.fullscreen).on("click",function(){a.toggleFullScreen()});var d=planeta.utils.readCookie("volume");if(d==null)d=0.5;this.setVolume(d);$(document).on("fullscreenchange mozfullscreenchange webkitfullscreenchange msfullscreenchange",function(){planeta.utils.log("fullscreen");
setTimeout(function(){if(!a.playingAd){a.showController();a.updateTimebar()}},0)});this.bindVideoEvents();this.showController(99999999999);this.config.autoplay&&this.play()},getAgeImage:function(a){switch(a){case "0+":return"/i/5/age0.png";case "6+":return"/i/5/age6.png";case "12+":return"/i/5/age12.png";case "16+":return"/i/5/age16.png";case "18+":return"/i/5/age18.png";default:return"/i/5/age18.png"}},init:function(){$("#"+this.config.placeholder).width(this.config.width).height(this.config.height);
if(swfobject.hasFlashPlayerVersion("9")&&0){var a=swfobject.getFlashPlayerVersion();planeta.utils.log("Flash Player v."+a.major+"."+a.minor+"."+a.release+" detected!");a=false;var d={menu:"true",flashvars:this.config.flashvars,wmode:"opaque",allowFullScreen:"true",allowScriptAccess:"always",bgcolor:"#000000"},c={id:this.config.placeholder+"_video",name:this.config.placeholder+"_video"};swfobject.embedSWF(this.config.swf_player_location+"?ver="+this.config.build+"&"+this.config.flashvars,this.config.placeholder,
this.config.width,this.config.height,"9.0.0","http://planeta-online.tv/swf/expressInstall.swf",a,d,c)}else{a=navigator.userAgent.toLowerCase();var e=true;if(/ipad/i.test(a))e=false;if(e){a='<div id="'+this.config.placeholder+'_wrapper" style="width:100%;height:100%">';a+='<video id="'+this.config.placeholder+'_video" class="po-video" poster="'+this.config.poster+'" ';if(this.config.tabindex)a+="tabindex="+this.config.tabindex;a+=' style="width:100%;height:100%">';a+="</video>";a+='<div id="'+this.config.placeholder+
'_controls" class="po-unselectable" style="display:none;position:absolute;top:0;left:0;color:white;width:100%;height:100%">';a+='<img id="'+this.config.placeholder+'_age" class="po-video-age" src="'+this.getAgeImage(this.config.age)+'" draggable=false>';a+='<div id="'+this.config.placeholder+'_title" class="po-video-title">'+this.config.title+"</div>";a+='<div id="'+this.config.placeholder+'_controlbar" class="po-controlbar">';a+='<div id="'+this.config.placeholder+'_playpause" class="po-play" title="\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u0432\u0438\u0434\u0435\u043e" />';
a+='<div id="'+this.config.placeholder+'_fullscreen" class="po-fullscreen" title="\u0420\u0430\u0437\u0432\u0435\u0440\u043d\u0443\u0442\u044c \u043d\u0430 \u0432\u0435\u0441\u044c \u044d\u043a\u0440\u0430\u043d" />';a+='<div id="'+this.config.placeholder+'_volumebar" class="po-volumebar">';a+='<div id="'+this.config.placeholder+'_volumelevel" class="po-volumebar-levelline"></div>';a+='<div id="'+this.config.placeholder+'_volumeticker" class="po-volumebar-ticker" style="position:relative;margin-top:-45px;"></div>';
a+="</div>";a+='<div id="'+this.config.placeholder+'_muteunmute" class="po-mute" title="\u0412\u044b\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0437\u0432\u0443\u043a" />';if(this.config.is_stream!=true){a+='<div id="'+this.config.placeholder+'_timebar" class="po-timebar">00:00 / 00:00</div>';a+='<div id="'+this.config.placeholder+'_progressbar" class="po-progressbar">';a+='<div id="'+this.config.placeholder+'_progressticker" class="po-progressbar-ticker" style="position:relative;left:-10px"></div>';
a+='<div id="'+this.config.placeholder+'_timetooltip" class="po-progressbar-timetooltip" style="position:relative;margin-top:-45px;display:none">00:00</div>';a+="</div>"}a+="</div>";a+="</div>"}else{a='<div id="'+this.config.placeholder+'_wrapper" style="width:100%;height:100%">';a+='<video id="'+this.config.placeholder+'_video" class="po-video" poster="'+this.config.poster+'" ';if(this.config.tabindex)a+="tabindex="+this.config.tabindex+" ";a+='style="width:100%;height:100%" controls>';a+="</video>"}a+=
"</div>";$("#"+this.config.placeholder).html(a);a=document.getElementById(this.config.placeholder+"_video");d=false;for(c=0;c<this.config.sources.length;c++){var b=this.config.sources[c];planeta.utils.dir(b);if(a.canPlayType(b.type)){d=true;a.setAttribute("src",b.src);a.load();break}}d||planeta.utils.log("ALERT! NO SUITABLE SOURCES FOUND!");var g=this;$(document).on("DOMContentLoaded",function(){planeta.utils.dir(g.config);e&&g.initHTML5Player()})}}};
planeta.AdController=function(a,d){this.player=a;this.type=d;this.adShown=this.vast30Ads=this.curVAST30Ad=this.curVASTProvider=0;this.videoSrc=this.player.video.src;this.videoTime=this.player.video.currentTime;this.videoVolume=this.player.video.volume;if(this.player.config.ads[this.type].length>0)planeta.utils.getVAST(this.player.config.ads[this.type][0],this,null);else this.type=="preroll"&&this.player.play()};
planeta.AdController.prototype={handleVAST:function(a,d){this.player.playingAd=1;planeta.utils.log("AdController.handleVAST => "+this.type);if(d==null)d=new planeta.AdPlayer(this);if(a&&a.VAST==null){planeta.utils.log("AdController.handleVAST: nobanner!");planeta.utils.trackGAEvent("advertisement","ad_vast_nobanner",this.type,0);this.nextAd(d,0)}else if(a&&a.VAST){planeta.utils.trackGAEvent("advertisement","ad_vast_received",this.type,0);if(a.VAST.Ad instanceof Array){var c=a.VAST.Ad[0];this.curVAST30Ad=
0;this.vast30Ads=[];for(var e=0;e<a.VAST.Ad.length;e++)this.vast30Ads[a.VAST.Ad[e]["@sequence"]-1]=a.VAST.Ad[e]}else{if(typeof a.VAST.Ad==="undefined"){planeta.utils.log("AdController.handleVAST: nobanner!");planeta.utils.trackGAEvent("advertisement","ad_vast_nobanner",this.type,0);this.nextAd(d,0);return}c=a.VAST.Ad}planeta.utils.log(c);d.init(c)}},nextAd:function(a,d){if(d)this.adShown=1;$("#"+a.placeholder+"_video").off();$("#"+a.placeholder+"_adcontrols").remove();$("#"+a.placeholder+"_adresume").remove();
if(this.vast30Ads!=0&&this.vast30Ads.length>this.curVAST30Ad+1){this.curVAST30Ad++;(new planeta.AdPlayer(this)).init(this.vast30Ads[this.curVAST30Ad])}else if(!this.adShown&&this.player.config.ads[this.type].length>this.curVASTProvider+1){this.curVASTProvider++;planeta.utils.getVAST(this.player.config.ads[this.type][this.curVASTProvider],this,null)}else{if(this.adShown){this.player.video.src=this.videoSrc;this.player.video.load();var c=this;$(this.player.video).on("loadedmetadata",function(){c.player.video.currentTime=
c.videoTime;c.player.video.volume=c.videoVolume})}this.player.playingAd=0;this.type=="postroll"&&this.player.video.pause();$("#"+a.placeholder+"_controls").show();this.player.bindVideoEvents();this.type=="preroll"&&this.player.play()}}};
planeta.AdPlayer=function(a){this.adController=a;this.vastSentThirdQuartile=this.vastSentMidpoint=this.vastSentFirstQuartile=this.vastSentStart=false;this.placeholder=this.adController.player.config.placeholder;this.vast_clickThrough=this.adclose=this.adgo=this.adtimer=this.admuteunmute=this.adtopline=this.adcontrols=this.advideo=0;this.vast_error=[];this.vast_impression=[];this.vast_creativeView=[];this.vast_start=[];this.vast_firstQuartile=[];this.vast_midpoint=[];this.vast_thirdQuartile=[];this.vast_complete=
[];this.vast_mute=[];this.vast_unmute=[];this.vast_pause=[];this.vast_resume=[];this.vast_close=[];this.vast_closeLinear=[];this.vast_rewind=[];this.vast_fullscreen=[];this.vast_expand=[];this.vast_collapse=[];this.vast_acceptInvitation=[];this.vast_skipTime2=this.vast_skipTime=this.vast_startTime=-1;this.vast_linkTxt="\u043f\u0435\u0440\u0435\u0439\u0442\u0438 \u043d\u0430 \u0441\u0430\u0439\u0442 \u0440\u0435\u043a\u043b\u0430\u043c\u043e\u0434\u0430\u0442\u0435\u043b\u044f";this.vast_isClickable=
1;this.vast_skipAd=[];this.vast_addClick=[];this.vast_clickTracking=[];planeta.AdPlayer.players[this.placeholder]=this};planeta.AdPlayer.players={};planeta.AdPlayer.fallbackVideoError=function(a){planeta.utils.log("planeta.AdPlayer.fallbackVideoError");planeta.AdPlayer.players[a]!="undefined"&&$(planeta.AdPlayer.players[a].advideo).trigger("vast_error");planeta.utils.trackGAEvent("advertisement","ad_error_cannot_play",this.adController.type,0)};
planeta.AdPlayer.prototype={makeUnselectable:function(a){a.addClass("po-unselectable").attr("unselectable","on").attr("draggable","false").on("dragstart",function(){return false});a.find("*").attr("draggable","false").attr("unselectable","on")},onLoadStart:function(){planeta.utils.log("loadstart");$(this.advideo).trigger("vast_creativeView")},onProgress:function(){planeta.utils.log("progress")},onSuspend:function(){planeta.utils.log("suspend")},onAbort:function(){planeta.utils.log("abort")},onEmptied:function(){planeta.utils.log("emptied")},
onStalled:function(){planeta.utils.log("stalled")},onLoadedMetadata:function(){planeta.utils.log("loadedmetadata")},onLoadedData:function(){planeta.utils.log("loadeddata")},onCanPlay:function(){planeta.utils.log("canplay")},onCanPlayThrough:function(){planeta.utils.log("canplaythrough")},onPlaying:function(){planeta.utils.log("playing")},onWaiting:function(){planeta.utils.log("waiting")},onSeeking:function(){planeta.utils.log("seeking")},onSeeked:function(){planeta.utils.log("seeked")},getDuration:function(){return this.advideo.duration},
onDurationChange:function(){planeta.utils.log("durationchange")},getCurrentTime:function(){return this.advideo.currentTime},setCurrentTime:function(a){this.advideo.currentTime=a},prevCurrentTime:0,onTimeUpdate:function(){var a=this.getCurrentTime(),d=this.getDuration();planeta.utils.log("onTimeUpdate: "+a);this.prevCurrentTime<=1&&a>1&&$(this.advideo).trigger("vast_impression");this.prevCurrentTime=a;if(!this.vastSentStart){this.vastSentStart=true;$(this.advideo).trigger("vast_start")}if(!this.vastSentFirstQuartile&&
a>d/4){this.vastSentFirstQuartile=true;$(this.advideo).trigger("vast_firstQuartile")}if(!this.vastSentMidpoint&&a>d/2){this.vastSentMidpoint=true;$(this.advideo).trigger("vast_midpoint")}if(!this.vastSentThirdQuartile&&a>d*3/4){this.vastSentThirdQuartile=true;$(this.advideo).trigger("vast_thirdQuartile")}d!=0&&this.updateTimerPie(Math.round(a*100/d));this.vast_skipTime2>=0&&this.vast_skipTime2<a&&$(this.adclose).show()},onPlay:function(){planeta.utils.log("onPlay")},onPause:function(){planeta.utils.log("onPause");
this.pause()},onResize:function(){planeta.utils.log("resize")},onVolumeChange:function(a){planeta.utils.log("volumechange");var d=a.target.volume;planeta.utils.createCookie("volume",d,30);a=a.target.id.substring(0,a.target.id.indexOf("_video"));$("#"+a+"_volumelevel").width(d*100+"%");$("#"+a+"_volumeticker").css({left:d*65-10})},toggleMuteUnmute:function(){this.isMuted()?this.unmute():this.mute()},mute:function(){this.adController.player.mute();$(this.advideo).trigger("vast_mute");$(this.admuteunmute).addClass("po-ad-unmute").removeClass("po-ad-mute").attr("title",
"\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0437\u0432\u0443\u043a")},unmute:function(){this.adController.player.unmute();$(this.advideo).trigger("vast_unmute");$(this.admuteunmute).addClass("po-ad-mute").removeClass("po-ad-unmute").attr("title","\u0412\u044b\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0437\u0432\u0443\u043a")},isMuted:function(){return this.advideo.muted},setVolume:function(a){if(this.advideo!=null)this.advideo.volume=a},onEnded:function(){planeta.utils.log("onEnded");planeta.utils.log(this.advideo);
$(this.advideo).trigger("vast_complete")},togglePlayPause:function(){this.isPaused()||this.isEnded()?this.play():$(this.advideo).trigger("pause")},play:function(){this.advideo.play();$(this.advideo).trigger("vast_resume")},pause:function(){this.advideo.pause();$(this.advideo).trigger("vast_pause")},isPaused:function(){return this.advideo.paused},isEnded:function(){return this.advideo.ended},toggleFullScreen:function(){this.isFullScreen()?this.closeFullScreen():this.goFullScreen()},goFullScreen:function(){var a=
this.wrapper,d=a.requestFullScreen||a.webkitRequestFullScreen||a.mozRequestFullScreen||a.msRequestFullscreen;d.call(a);$(this.fullscreen).attr("title","\u0417\u0430\u043a\u0440\u044b\u0442\u044c \u043f\u043e\u043b\u043d\u043e\u044d\u043a\u0440\u0430\u043d\u043d\u044b\u0439 \u0440\u0435\u0436\u0438\u043c");this.makeUnselectable($("#"+this.placeholder))},closeFullScreen:function(){if(document.cancelFullScreen)document.cancelFullScreen();else if(document.mozCancelFullScreen)document.mozCancelFullScreen();
else if(document.webkitCancelFullScreen)document.webkitCancelFullScreen();else document.msExitFullscreen&&document.msExitFullscreen();$(this.fullscreen).attr("title","\u0420\u0430\u0437\u0432\u0435\u0440\u043d\u0443\u0442\u044c \u043d\u0430 \u0432\u0435\u0441\u044c \u044d\u043a\u0440\u0430\u043d")},isFullScreen:function(){if(document.fullscreen)return true;if(document.mozFullScreen)return true;if(document.webkitIsFullScreen)return true;if(document.msFullscreenElement)return true;return window.fullScreen||
window.innerWidth==screen.width&&window.innerHeight==screen.height?true:false},updateProgress:function(){},onVastClickThrough:function(){for(var a=0;a<this.vast_clickTracking.length;a++){planeta.utils.log("onVastClickThrough: "+this.vast_clickTracking[a]);planeta.utils.trackEvent(this.vast_clickTracking[a])}this.advideo.pause();planeta.utils.log("onVastClickThrough: "+this.vast_clickThrough);a=document.createElement("a");a.href=this.vast_clickThrough;a.target="_blank";document.body.appendChild(a);
a.click();a.parentNode.removeChild(a);$("#"+this.placeholder+"_adresume").show();planeta.utils.trackGAEvent("advertisement","ad_clickthrough",this.adController.type,0)},onVastAddClick:function(){for(var a=0;a<this.vast_addClick.length;a++){planeta.utils.log("onVastAddClick: "+this.vast_addClick[a]);planeta.utils.trackEvent(this.vast_addClick[a])}for(a=0;a<this.vast_clickTracking.length;a++){planeta.utils.log("onVastClickThrough: "+this.vast_clickTracking[a]);planeta.utils.trackEvent(this.vast_clickTracking[a])}this.advideo.pause();
planeta.utils.log("onVastAddClick: "+this.vast_clickThrough);a=document.createElement("a");a.href=this.vast_clickThrough;a.target="_blank";document.body.appendChild(a);a.click();a.parentNode.removeChild(a);$("#"+this.placeholder+"_adresume").show();planeta.utils.trackGAEvent("advertisement","ad_click",this.adController.type,0)},onVastError:function(){for(var a=0;a<this.vast_error.length;a++){planeta.utils.log("onVastError: "+this.vast_error[a]);planeta.utils.trackEvent(this.vast_error[a])}planeta.utils.trackGAEvent("advertisement",
"ad_vast_error",this.adController.type,0);this.adController.nextAd(this,0)},onError:function(a){this.onVastError(a)},onVastCreativeView:function(){for(var a=0;a<this.vast_creativeView.length;a++){planeta.utils.log("onVastCreativeView: "+this.vast_creativeView[a]);planeta.utils.trackEvent(this.vast_creativeView[a])}},onVastImpression:function(){for(var a=0;a<this.vast_impression.length;a++){planeta.utils.log("onVastImpression: "+this.vast_impression[a]);planeta.utils.trackEvent(this.vast_impression[a])}planeta.utils.trackGAEvent("advertisement",
"ad_impression",this.adController.type,0)},onVastStart:function(){for(var a=0;a<this.vast_start.length;a++){planeta.utils.log("onVastStart: "+this.vast_start[a]);planeta.utils.trackEvent(this.vast_start[a])}planeta.utils.trackGAEvent("advertisement","ad_start",this.adController.type,0)},onVastPause:function(){for(var a=0;a<this.vast_pause.length;a++){planeta.utils.log("onVastPause: "+this.vast_pause[a]);planeta.utils.trackEvent(this.vast_pause[a])}planeta.utils.trackGAEvent("advertisement","ad_pause",
this.adController.type,0)},onVastResume:function(){for(var a=0;a<this.vast_resume.length;a++){planeta.utils.log("onVastResume: "+this.vast_resume[a]);planeta.utils.trackEvent(this.vast_resume[a])}$("#"+this.placeholder+"_adresume").hide();this.advideo.play();planeta.utils.trackGAEvent("advertisement","ad_resume",this.adController.type,0)},onVastClose:function(){for(var a=0;a<this.vast_close.length;a++){planeta.utils.log("onVastClose: "+this.vast_close[a]);planeta.utils.trackEvent(this.vast_close[a])}this.advideo.pause();
this.adController.nextAd(this,1);planeta.utils.trackGAEvent("advertisement","ad_close",this.adController.type,0)},onVastFirstQuartile:function(){for(var a=0;a<this.vast_firstQuartile.length;a++){planeta.utils.log("onVastFirstQuartile: "+this.vast_firstQuartile[a]);planeta.utils.trackEvent(this.vast_firstQuartile[a])}planeta.utils.trackGAEvent("advertisement","ad_firstquartile",this.adController.type,0)},onVastMidpoint:function(){for(var a=0;a<this.vast_midpoint.length;a++){planeta.utils.log("onVastMidpoint: "+
this.vast_midpoint[a]);planeta.utils.trackEvent(this.vast_midpoint[a])}planeta.utils.trackGAEvent("advertisement","ad_midpoint",this.adController.type,0)},onVastThirdQuartile:function(){for(var a=0;a<this.vast_thirdQuartile.length;a++){planeta.utils.log("onVastThirdQuartile: "+this.vast_thirdQuartile[a]);planeta.utils.trackEvent(this.vast_thirdQuartile[a])}planeta.utils.trackGAEvent("advertisement","ad_thirdquartile",this.adController.type,0)},onVastComplete:function(){for(var a=0;a<this.vast_complete.length;a++){planeta.utils.log("onVastComplete: "+
this.vast_complete[a]);planeta.utils.trackEvent(this.vast_complete[a])}this.adController.nextAd(this,1);planeta.utils.trackGAEvent("advertisement","ad_complete",this.adController.type,0)},onVastSkip:function(){for(var a=0;a<this.vast_skipAd.length;a++){planeta.utils.log("onVastSkip: "+this.vast_skipAd[a]);planeta.utils.trackEvent(this.vast_skipAd[a])}this.adController.nextAd(this,1);planeta.utils.trackGAEvent("advertisement","ad_skip",this.adController.type,0)},onVastMute:function(){for(var a=0;a<
this.vast_mute.length;a++){planeta.utils.log("onVastMute: "+this.vast_mute[a]);planeta.utils.trackEvent(this.vast_mute[a])}planeta.utils.trackGAEvent("advertisement","ad_mute",this.adController.type,0)},onVastUnmute:function(){for(var a=0;a<this.vast_unmute.length;a++){planeta.utils.log("onVastUnmute: "+this.vast_unmute[a]);planeta.utils.trackEvent(this.vast_unmute[a])}planeta.utils.trackGAEvent("advertisement","ad_unmute",this.adController.type,0)},updateTimerPie:function(a){var d='<div class="po-ad-timer"><div class="po-pieback"></div><div class="po-pieback po-fill"></div><div id="po-slice"'+
(a>50?' class="po-gt50"':"")+'><div class="po-pie"></div>'+(a>50?'<div class="po-pie po-fill"></div>':"")+"</div>";if(this.vast_skipTime>=0)if(this.vast_skipTime<=this.getCurrentTime()){d+='<div style="width:150px;font-size:14px;cursor:pointer;padding:0 0 0 25px">\u043f\u0440\u043e\u043f\u0443\u0441\u0442\u0438\u0442\u044c \u0440\u0435\u043a\u043b\u0430\u043c\u0443</div>';var c=this;$("#"+this.placeholder+"_adtimer").width("170px").off("click").on("click",function(){$(c.advideo).trigger("vast_skip");
return false})}d+="</div>";$(this.adtimer).html(d);a=3.6*a;$("#"+this.placeholder+"_adtimer > .po-ad-timer > #po-slice .po-pie").css({"-moz-transform":"rotate("+a+"deg)","-webkit-transform":"rotate("+a+"deg)","-o-transform":"rotate("+a+"deg)",transform:"rotate("+a+"deg)"})},applyTrackingEvents:function(a){for(var d=0;d<a.length;d++){var c=a[d];switch(c["@event"]){case "creativeView":this.vast_creativeView.push(c["#cdata"]);break;case "start":this.vast_start.push(c["#cdata"]);break;case "firstQuartile":this.vast_firstQuartile.push(c["#cdata"]);
break;case "midpoint":this.vast_midpoint.push(c["#cdata"]);break;case "thirdQuartile":this.vast_thirdQuartile.push(c["#cdata"]);break;case "complete":this.vast_complete.push(c["#cdata"]);break;case "mute":this.vast_mute.push(c["#cdata"]);break;case "unmute":this.vast_unmute.push(c["#cdata"]);break;case "pause":this.vast_pause.push(c["#cdata"]);break;case "resume":this.vast_resume.push(c["#cdata"]);break;case "close":this.vast_close.push(c["#cdata"]);break;case "closeLinear":this.vast_close.push(c["#cdata"]);
break;case "rewind":this.vast_rewind.push(c["#cdata"]);break;case "fullscreen":this.vast_fullscreen.push(c["#cdata"]);break;case "expand":this.vast_expand.push(c["#cdata"]);break;case "collapse":this.vast_collapse.push(c["#cdata"]);break;case "acceptInvitation":this.vast_acceptInvitation.push(c["#cdata"]);break}}},applyExtensions:function(a){if(a!=null)for(var d=0;d<a.length;d++){var c=a[d],e=c["#cdata"]?c["#cdata"]:c["#text"];switch(c["@type"]){case "startTime":this.vast_startTime=parseInt(e.substring(0,
2))*60+parseInt(e.substring(3,5));break;case "skipTime":this.vast_skipTime=parseInt(e.substring(0,2))*60+parseInt(e.substring(3,5));break;case "skipTime2":this.vast_skipTime2=parseInt(e.substring(0,2))*60+parseInt(e.substring(3,5));break;case "linkTxt":this.vast_linkTxt=c=e?decodeURIComponent(e):e;$(this.adgo).html(c);break;case "isClickable":this.vast_isClickable=e;break;case "skipAd":this.vast_skipAd.push(e);break;case "addClick":this.vast_addClick.push(e);break;case "controls":break}}},init:function(a){planeta.utils.log("AdPlayer.init");
if(a.Wrapper){planeta.utils.log("Wrapper detected: "+a.Wrapper.VASTAdTagURI["#cdata"]);planeta.utils.getVAST(a.Wrapper.VASTAdTagURI["#cdata"],this.adController,this);a.Wrapper.Impression&&this.vast_impression.push(a.Wrapper.Impression["#cdata"]);a.Wrapper.Error&&this.vast_error.push(a.Wrapper.Error["#cdata"]);var d=a.Wrapper.Creatives.Creative.Linear.VideoClicks;if(d&&d.ClickTracking)if(d.ClickTracking.length)for(var c=0;c<d.ClickTracking.length;c++)this.vast_clickTracking.push(d.ClickTracking[c]["#cdata"]);
else this.vast_clickTracking.push(d.ClickTracking["#cdata"]);a.Wrapper.Creatives.Creative.Linear.TrackingEvents&&this.applyTrackingEvents(a.Wrapper.Creatives.Creative.Linear.TrackingEvents.Tracking);a.Wrapper.Extensions&&this.applyExtensions(a.Wrapper.Extensions.Extension)}else{planeta.utils.log(this.adController.player);this.adController.player.video.pause();$(this.adController.player.playpause).addClass("po-play").removeClass("po-pause").attr("title","\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u0432\u0438\u0434\u0435\u043e");
d=a.InLine.Creatives.Creative;planeta.utils.log("creative:");planeta.utils.log(d);if(d.Linear){var e;e=d.Linear.MediaFiles.MediaFile.length?d.Linear.MediaFiles.MediaFile:[d.Linear.MediaFiles.MediaFile];c='<div id="'+this.placeholder+'_adcontrols" class="po-ad-controls po-unselectable" style="display:block;position:absolute;top:0;left:0;color:white;width:100%;height:100%">';c+='<div id="'+this.placeholder+'_adtopline" class="po-ad-topline">';c+='<div style="float:left;margin:-2px 10px">\u0440\u0435\u043a\u043b\u0430\u043c\u0430 \u043d\u0430 planeta-online</div>';
c+='<div id="'+this.placeholder+'_adclose" style="display:none;cursor:pointer;float:right;margin:-2px 2px"><div style="margin:2px;" class="po-ad-close"></div>\u0437\u0430\u043a\u0440\u044b\u0442\u044c</div>';c+="</div>";c+='<div id="'+this.placeholder+'_admuteunmute" ';c+=this.adController.player.isMuted()?'class="po-ad-unmute" title="\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0437\u0432\u0443\u043a"':'class="po-ad-mute" title="\u0412\u044b\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0437\u0432\u0443\u043a"';
c+="></div>";c+='<div id="'+this.placeholder+'_adtimer" class="po-ad-timercontainer"></div>';c+='<div id="'+this.placeholder+'_adgo" class="po-ad-go">'+this.vast_linkTxt+"</div>";c+="</div>";c+='<div id="'+this.placeholder+'_adresume" style="cursor:pointer;position:absolute;top:0;left:0;width:100%;height:100%;display:none"><div class="po-ad-resume"></div>';$("#"+this.placeholder+"_video").off();$("#"+this.placeholder+"_controls").hide();$("#"+this.placeholder+"_wrapper").append(c);planeta.utils.log(c);
var b=this;this.advideo=document.getElementById(this.placeholder+"_video");this.adcontrols=document.getElementById(this.placeholder+"_adcontrols");this.adtopline=document.getElementById(this.placeholder+"_adtopline");this.adclose=document.getElementById(this.placeholder+"_adclose");this.admuteunmute=document.getElementById(this.placeholder+"_admuteunmute");this.adtimer=document.getElementById(this.placeholder+"_adtimer");this.adgo=document.getElementById(this.placeholder+"_adgo");var g=false;for(c=
0;c<e.length;c++){var i=e[c];planeta.utils.dir(i);if(this.advideo.canPlayType(i["@type"])){g=true;this.advideo.setAttribute("src",i["#cdata"]);this.advideo.load();this.advideo.play();break}}$("#"+this.placeholder+"_adresume").on("click",function(){$(b.advideo).trigger("vast_resume")});this.setVolume(0.4);c=navigator.userAgent.toLowerCase();b.vast_isClickable!=1&&$(this.adgo).hide();if(!/ipad/i.test(c)&&!/iphone/i.test(c)){$(this.adgo).hide();$(this.adcontrols).on("mousemove",function(){b.vast_isClickable==
1&&$(b.adgo).show();$(b.adtopline).addClass("po-ad-topline-hovered").removeClass("po-ad-topline")}).on("mouseleave",function(){$(b.adgo).hide();$(b.adtopline).addClass("po-ad-topline").removeClass("po-ad-topline-hovered")});$(this.advideo).on("contextmenu",function(){return false}).on("mousemove",function(){b.vast_isClickable==1&&$(b.adgo).show();$(b.adtopline).addClass("po-ad-topline-hovered").removeClass("po-ad-topline");return false}).on("mouseleave",function(){$(b.adgo).hide();$(b.adtopline).addClass("po-ad-topline").removeClass("po-ad-topline-hovered");
return false})}$(this.adcontrols).on("click",function(){b.vast_isClickable==1&&$(b.advideo).trigger("vast_click");return false});$(this.advideo).on("click",function(){b.vast_isClickable==1&&$(b.advideo).trigger("vast_click");return false});$(this.adgo).on("click",function(){b.vast_isClickable==1&&$(b.advideo).trigger("vast_addclick");return false});$(this.adclose).on("click",function(){$(b.advideo).trigger("vast_closeLinear");return false});$(this.admuteunmute).on("click",function(){b.toggleMuteUnmute();
return false});if(d.Linear.VideoClicks&&d.Linear.VideoClicks.ClickThrough)this.vast_clickThrough=d.Linear.VideoClicks.ClickThrough["#cdata"];a.InLine.Impression&&this.vast_impression.push(a.InLine.Impression["#cdata"]);a.InLine.Error&&this.vast_error.push(a.InLine.Error["#cdata"]);d.Linear.TrackingEvents&&this.applyTrackingEvents(d.Linear.TrackingEvents.Tracking);a.InLine.Extensions&&this.applyExtensions(a.InLine.Extensions.Extension);$(this.advideo).on("contextmenu",function(){}).on("loadstart",
function(f){b.onLoadStart(f)}).on("progress",function(f){b.onProgress(f)}).on("suspend",function(f){b.onSuspend(f)}).on("abort",function(f){b.onAbort(f)}).on("emptied",function(f){b.onEmptied(f)}).on("stalled",function(f){b.onStalled(f)}).on("loadedmetadata",function(f){b.advideo.currentTime=0.01;b.onLoadedMetadata(f)}).on("loadeddata",function(f){b.onLoadedData(f)}).on("canplay",function(f){b.onCanPlay(f)}).on("canplaythrough",function(f){b.onCanPlayThrough(f)}).on("playing",function(f){b.onPlaying(f)}).on("waiting",
function(f){b.onWaiting(f)}).on("seeking",function(f){b.onSeeking(f)}).on("seeked",function(f){b.onSeeked(f)}).on("durationchange",function(f){b.onDurationChange(f)}).on("timeupdate",function(f){b.onTimeUpdate(f)}).on("play",function(f){b.onPlay(f)}).on("pause",function(f){b.advideo.ended||b.onPause(f)}).on("ratechange",function(f){b.onRateChange(f)}).on("resize",function(f){b.onResize(f)}).on("volumechange",function(f){b.onVolumeChange(f)}).on("ended",function(f){b.onEnded(f)}).on("error",function(f){b.onError(f)}).on("vast_error",
function(){b.onVastError()}).on("vast_click",function(){b.onVastClickThrough()}).on("vast_addclick",function(){b.onVastAddClick()}).on("vast_impression",function(){b.onVastImpression()}).on("vast_creativeView",function(){b.onVastCreativeView()}).on("vast_start",function(){b.onVastStart()}).on("vast_firstQuartile",function(){b.onVastFirstQuartile()}).on("vast_midpoint",function(){b.onVastMidpoint()}).on("vast_thirdQuartile",function(){b.onVastThirdQuartile()}).on("vast_complete",function(){b.onVastComplete()}).on("vast_mute",
function(){b.onVastMute()}).on("vast_unmute",function(){b.onVastUnmute()}).on("vast_pause",function(){b.onVastPause()}).on("vast_resume",function(){b.onVastResume()}).on("vast_close",function(){b.onVastClose()}).on("vast_closeLinear",function(){b.onVastClose()}).on("vast_rewind",function(){b.onVastRewind()}).on("vast_fullscreen",function(){b.onVastFullscreen()}).on("vast_expand",function(){b.onVastExpand()}).on("vast_collapse",function(){b.onVastCollapse()}).on("vast_acceptInvitation",function(){b.onVastAcceptInvitation()}).on("vast_skip",
function(){b.onVastSkip()});if(!g){planeta.utils.log("ALERT! NO SUITABLE SOURCES FOUND!");$(b.advideo).trigger("vast_error")}}}}};
